CREATE TABLE IF NOT EXISTS wcf_webhook_delivery (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    wechat_account_id BIGINT NOT NULL,
    event_id BIGINT NULL,
    delivery_type VARCHAR(64) NOT NULL,
    target_url VARCHAR(1024) DEFAULT '',
    request_body LONGTEXT,
    response_body LONGTEXT,
    response_code INT NULL,
    delivery_status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 1,
    error_message TEXT,
    trace_id VARCHAR(255) DEFAULT '',
    create_user_id BIGINT NULL,
    update_user_id BIGINT NULL,
    company_id BIGINT NULL,
    dept_id BIGINT NULL,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    is_deleted INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    KEY idx_wcf_webhook_delivery_account (wechat_account_id),
    KEY idx_wcf_webhook_delivery_event (event_id),
    KEY idx_wcf_webhook_delivery_trace (trace_id)
);
